---
applications:
- guillotina.contrib.catalog.pg
- guillotina.contrib.swagger
- guillotina_dbusers
- guillotina_amqp
- guillotina_notification
- guillotina.contrib.mailer
mailer:
  default_sender: foo@bar.com
  endpoints:
    default:
      type: smtp
      host: localhost
      port: 25
  utility: guillotina.contrib.mailer.utility.PrintingMailerUtility
databases:
  db:
    storage: postgresql
    dsn: postgresql://postgres@localhost:5432/guillotina
    read_only: false
host: 127.0.0.1
port: 8080
root_user:
  password: root
auth_extractors:
- guillotina.auth.extractors.BearerAuthPolicy
- guillotina.auth.extractors.BasicAuthPolicy
- guillotina.auth.extractors.WSTokenAuthPolicy
auth_token_validators:
- guillotina.auth.validators.SaltedHashPasswordValidator
- guillotina.auth.validators.JWTValidator
cors:
  allow_origin:
  - http://localhost:8080
  - "chrome-extension://*"
  allow_methods:
  - GET
  - POST
  - DELETE
  - HEAD
  - PATCH
  - PUT
  - OPTIONS
  allow_headers:
  - "*"
  expose_headers:
  - "*"
  allow_credentials: true
  max_age: 3660
jwk:
  k: aDuvgVVf1q5vF9A6syXvnM4oIPsBadLE3OScrGCLtfk
  kty: oct
jwt:
  secret: foobar
  algorithm: HS256
